runtime: python312  # 最新のPython 3.12ランタイムに変更
instance_class: F1
env: standard

runtime_config:
  document_root: www

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 3
  max_concurrent_requests: 200

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /favicon.ico
  static_files: www/favicon.ico
  upload: www/favicon.ico

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

# .gitフォルダを除外
skip_files:
- ^(.*/)?\.git(/.*)?$
